// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3rKDzumgzJLnm0xfpE-CYn_TFG_9IgI',
    appId: '1:325943660774:web:7ce1f0f5bb55b995bbab27',
    messagingSenderId: '325943660774',
    projectId: 'timex-9ce03',
    authDomain: 'timex-9ce03.firebaseapp.com',
    storageBucket: 'timex-9ce03.firebasestorage.app',
    measurementId: 'G-DSQ8157ZZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJplGXQfX7FqOJkI2UCcgDpPb10pSp3tM',
    appId: '1:325943660774:android:a4e346ecc8cc4217bbab27',
    messagingSenderId: '325943660774',
    projectId: 'timex-9ce03',
    storageBucket: 'timex-9ce03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI2UHY8QnTv7fKeUY-BYaEBFoXO0YDygA',
    appId: '1:325943660774:ios:7d42c73227bc04f1bbab27',
    messagingSenderId: '325943660774',
    projectId: 'timex-9ce03',
    storageBucket: 'timex-9ce03.firebasestorage.app',
    iosBundleId: 'com.example.timex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI2UHY8QnTv7fKeUY-BYaEBFoXO0YDygA',
    appId: '1:325943660774:ios:7d42c73227bc04f1bbab27',
    messagingSenderId: '325943660774',
    projectId: 'timex-9ce03',
    storageBucket: 'timex-9ce03.firebasestorage.app',
    iosBundleId: 'com.example.timex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy3rKDzumgzJLnm0xfpE-CYn_TFG_9IgI',
    appId: '1:325943660774:web:440d2d5124a7e82abbab27',
    messagingSenderId: '325943660774',
    projectId: 'timex-9ce03',
    authDomain: 'timex-9ce03.firebaseapp.com',
    storageBucket: 'timex-9ce03.firebasestorage.app',
    measurementId: 'G-837HD7W8N7',
  );
}
